config-sparse:
  modules:
    maploader:
      config:
        extra-map-directory:
          contents:
            suggested-value: ucp/plugins/Golden-Olive-Edition-*/resources/maps
  plugins: {}
meta:
  version: 1.0.0
